waypoint_detector_node:
  ros__parameters:
    spawn_x: -21.0
    spawn_y: -47.0
    waypoints: [-19.0, -47.0,  -15.0, -47.0,  -21.0, -43.0]  # real world coords
    waypoint_names: ["WP-1", "WP-2", "WP-3"]
    arrival_radius: 0.5

    # How often to publish /waypoint_status (seconds)
    status_interval: 1.0

    # Primary odometry topic
    odom_topic: "/diff_drive_controller/odom"
